services:
  redis:
    #container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile/
    image: backend
    depends_on:
      - redis
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    image: client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - client/.env
