const products = [
  {
    id: "1",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "2",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "3",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "4",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "5",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "6",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Beyaz",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "7",
    name: "Apple iPhone 11 Pro ",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 3000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "8",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "9",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Lacivert",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "10",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Lacivert",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "11",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Lacivert",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "12",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Lacivert",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 45,
  },
  {
    id: "13",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Lacivert",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "14",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Lacivert",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 35,
  },
  {
    id: "15",
    name: "Apple iPhone 11 Pro ",
    image: "imageurl",
    brand: "Apple",
    color: "Lacivert",
    price: 3000,
    createdDate: new Date(),
    discountPercentage: 40,
  },
  {
    id: "16",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Sarı",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "17",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Sarı",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "18",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Sarı",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 15,
  },
  {
    id: "19",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Apple",
    color: "Sarı",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "20",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Samsung",
    color: "Sarı",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 35,
  },
  {
    id: "22",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Samsung",
    color: "Sarı",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "23",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Samsung",
    color: "Sarı",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 15,
  },
  {
    id: "24",
    name: "Apple iPhone 11 Pro ",
    image: "imageurl",
    brand: "Samsung",
    color: "Beyaz",
    price: 3000,
    createdDate: new Date(),
    discountPercentage: 40,
  },
  {
    id: "25",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Samsung",
    color: "Beyaz",
    price: 3000,
    createdDate: new Date(),
    discountPercentage: 40,
  },
  {
    id: "26",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Samsung",
    color: "Kırmızı",
    price: 3000,
    createdDate: new Date(),
    discountPercentage: 20,
  },
  {
    id: "27",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Nokia",
    color: "Siyah",
    price: 100,
    createdDate: new Date(),
    discountPercentage: 5,
  },
  {
    id: "28",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "LG",
    color: "Siyah",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "29",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Xiaomi",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "30",
    name: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    image: "imageurl",
    brand: "Xiaomi",
    color: "Siyah",
    price: 1000,
    createdDate: new Date(),
    discountPercentage: 0,
  },
  {
    id: "31",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "General Mobile",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 25,
  },
  {
    id: "32",
    name: "Apple iPhone 11 Pro ",
    image: "imageurl",
    brand: "Xiaomi",
    color: "Siyah",
    price: 3000,
    createdDate: new Date(),
    discountPercentage: 20,
  },
  {
    id: "33",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 32,
  },
  {
    id: "34",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "35",
    name: "Apple iPhone 11 Pro ",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 3000,
    createdDate: new Date(),
    discountPercentage: 30,
  },
  {
    id: "36",
    name: "Apple iPhone 11",
    image: "imageurl",
    brand: "Apple",
    color: "Siyah",
    price: 10000,
    createdDate: new Date(),
    discountPercentage: 15,
  },
];
module.exports = products;